32
Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан массив размера  N . После каждого отрицательного элемента массива вставить элемент с нулевым значением.
б) Дана матрица размера  M×N . Упорядочить ее столбцы так, чтобы их последние элементы образовывали убывающую последовательность.

In [3]:
#пункт а
import numpy as np

def zero(arr):
    ind = np.where(arr < 0)[0]
    massiv = np.insert(arr, ind + 1, 0)
    return massiv

array = np.array([5, 4, 3, 2, 1, 0, -1, -2, -3, -4])
mas = zero(array)
print(mas)

[ 5  4  3  2  1  0 -1  0 -2  0 -3  0 -4  0]


б) Дана матрица размера M×N . Упорядочить ее столбцы так, чтобы их последние элементы образовывали убывающую последовательность.

In [2]:
#пункт б
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 9, 7, 8])
array = array.reshape(3, 3)#изменение размерности
ind = np.argsort(array[-1, :])#получаем отсортированные индексы последних элементов каждого столбца
mas = array[:, ind]
print(mas)

[[2 3 1]
 [5 6 4]
 [7 8 9]]


33
Дан стек. Необходимо найти среднее арифметическое всех его элементов.

In [4]:
class Node():
    def __init__(self, value, next=None, prev=None):
        self.next = next
        self.prev = prev
        self.value = value

class Stack():
    def __init__(self, value):
        self.head = Node(value=value, prev=None, next=None)
        self.tail = self.head
        self.size = 1

    def push(self, value):
        if self.size == 0:
            self.head = Node(value=value, next=None, prev=None)
            self.tail = self.head
            self.size = 1
            return
        tmp = self.tail
        tmp.next = Node(value=value, next=None, prev=tmp)
        self.tail = tmp.next
        self.size += 1

    def pop(self):
        if self.size <= 0:
            print("ERROR")
            return
        if self.size == 1:
            self.head = None
            self.tail = None
            self.size -= 1
            return
        tmp = self.tail
        self.tail = tmp.prev
        self.tail.next = None
        self.size -= 1

    def peek(self):
        return self.head.value

    def is_empty(self):
        return self.size == 0

    def size(self):
        return self.size

    def output(self):
        tmp = self.head
        while tmp:
            print(tmp.value, end=" ")
            tmp = tmp.next
        print("")

    def sum(self):
        tmp = self.head
        summa = 0
        while tmp:
            summa += tmp.value
            tmp = tmp.next
        return summa

    def srzn(self):
        return self.sum() / self.size


stack = Stack(5)  # "5"
stack.pop()  # ""
stack.pop()  # "ERROR"
stack.output()  # ""
print(stack.size)  # 0
stack.push(4)  # "4"
stack.push(6)  # "4 6"
stack.push(7)  # "4 6 7"
stack.output()
print(stack.size)  # 3
stack.pop()  # "4 6"
stack.output()
print(stack.size)  # 2
print(stack.srzn())  # 5.0

ERROR

0
4 6 7 
3
4 6 
2
5.0


34
Создать класс очереди, который будет поддерживать операции добавления элемента в конец очереди и удаления элемента из середины очереди по значению.

In [ ]:
class Node():
    def __init__(self, value, next=None):
        self.next = next
        self.value = value

class Queue():
    def __init__(self, value):
        self.head = Node(value=value)
        self.size = 1

    def enqueue(self, item):
        if self.size == 0:
            return Node(value=item)
        tmp = self.head
        while tmp.next:
            tmp = tmp.next
        tmp.next = Node(value=item)
        self.size += 1

    def dequeue(self):
        if self.size <= 0:
            print("ERROR")
            return
        if self.size == 1:
            self.head = None
            return
        self.head = self.head.next
        self.size -= 1
        return

    def peek(self):
        return self.head.value

    def is_empty(self):
        if self.size:
            return False
        return True

    def size(self):
        return self.size

    def output(self):
        tmp = self.head
        while tmp:
            print(tmp.value, end=" ")
            tmp = tmp.next
        print("")

    def del_centr(self, item):
        tmp = self.head

        while tmp.next:
            if tmp.next.value == item:
                tmp.next = tmp.next.next
                return
            tmp = tmp.next
        print("Item not found in queue")

queue = Queue(5)
queue.enqueue(4)
queue.enqueue(7)
queue.dequeue()
queue.output()
print(queue.size)
queue.enqueue(10)
queue.enqueue(8)
queue.output()
queue.del_centr(10)
queue.del_centr(10)
queue.output()